export default {
	login: "Devoidsm",
	id: 136974376,
	node_id: "U_kgDOCCoQKA",
	avatar_url: "https://avatars.githubusercontent.com/u/136974376?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/Devoidsm",
	html_url: "https://github.com/Devoidsm",
	followers_url: "https://api.github.com/users/Devoidsm/followers",
	following_url: "https://api.github.com/users/Devoidsm/following{/other_user}",
	gists_url: "https://api.github.com/users/Devoidsm/gists{/gist_id}",
	starred_url: "https://api.github.com/users/Devoidsm/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/Devoidsm/subscriptions",
	organizations_url: "https://api.github.com/users/Devoidsm/orgs",
	repos_url: "https://api.github.com/users/Devoidsm/repos",
	events_url: "https://api.github.com/users/Devoidsm/events{/privacy}",
	received_events_url: "https://api.github.com/users/Devoidsm/received_events",
	type: "User",
	site_admin: false,
	name: "Jarryd",
	company: null,
	blog: "",
	location: null,
	email: null,
	hireable: 'Yes',
	bio: "I'm very new to the developer scene and wish to strive for greatness ",
	twitter_username: null,
	public_repos: 5,
	public_gists: 0,
	followers: 1,
	following: 1,
	created_at: "2023-06-18T12:24:18Z",
	updated_at: "2023-06-22T14:43:13Z"
};